version: '3.8'
services:
  backstage:
    image: backstage
    environment:
      # This value must match the name of the postgres configuration block.
      POSTGRES_PORT: ${POSTGRES_PORT}
      # POSTGRES_HOST: ${POSTGRES_HOST}
      # POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      SONARQUBE_TOKEN: ${SONARQUBE_TOKEN}
      GITHUB_BKSTG_CLIENT_ID: ${GITHUB_BKSTG_CLIENT_ID}
      GITHUB_BKSTG_CLIENT_SECRET: ${GITHUB_BKSTG_CLIENT_SECRET}
    ports:
      - "7007:7007"

  db:
    image: postgres
    restart: always
    environment:
    # NOT RECOMMENDED for a production environment. Trusts all incomming
    # connections.
      POSTGRES_HOST_AUTH_METHOD: trust
