site_name: 'Bootstrap'
site_description: 'Running mkdocs for the first time'

plugins:
  - techdocs-core

nav:
  - Backstage:
    - Definitions: backstage-definition.md
    - Getting Started: getting-started.md
    - Docker: docker.md
    - Dockerization: dockerisation.md
    - DataBase: database.md
  - Plugins: 
    - Creating Plugins: plugins/creating-a-plugin.md
    - SonarQube: plugins/sonarqube
    - Search: plugins/search.md
