site_name: 'Bootstrap'
site_description: 'Running mkdocs for the first time'

plugins:
  - techdocs-core

nav:
  - Backstage:
    - Getting Started: getting-started.md
    - Dockerization: dockerisation.md
    - Docker: docker.md
    - Dockerization: dockerisation.md
  - Plugins: 
    - SonarQube: sonarqube.md
